### PR TITLE
Ensure that $channels (if provided) is passed along when using sendNow()

### PR DESCRIPTION
**Pull request by felipehertzer**
Hey @tibbsa 

It was duplicating the notifications when send a notification via multiple channels, due to missing the target channel variable.

Thanks.

### CODE REVIEW

**Comment by tibbsa** [comment]
The only 'send' function that this changes is the one used for a notification that is NOT subject to rate limiting.  That may well be solving a problem (passing along `$channels` is probably important!).  But (would that not also apply to notifications flowing through `sendWithRateLimitCheck()`?

**Comment by felipehertzer** [comment]
@tibbsa That is right, I was having problems with Notifications without ratelimit.

**Comment by tibbsa** [comment]
Ok, I will add tests and validate.  Thank you.

**Comment by felipehertzer** [comment]
Sorry, I just got what you mean, I think it needs to pass channels on sendWithRateLimitCheck as well.

**Comment by tibbsa** [comment]
Good catch.  Thank you for this.   I will push out an update now.

**Pull request merged**
