### PR TITLE
php and laravel 8 support

### LINKED ISSUE #12: Issue on laravel 8
Do this support laravel 8?

### PR DESCRIPTION
**Pull request by myckhel**
should fix https://github.com/jamesmills/laravel-notification-rate-limit/issues/12

tested on real project with php and laravel v8

### CODE REVIEW

**Comment by jamesmills** [comment]
Thanks @myckhel this has been tagged as `1.1.0`

**Comment by myckhel** [comment]
> Thanks @myckhel this has been tagged as `1.1.0`

maybe we are still waiting for the `v1.1.0` release tag

**Comment by MaxChew** [comment]
@jamesmills can i know when the v1.1.0 is ready? coz the v1.0.0 still no supporting the laravel 8.. sorry bro hope you release the tag.

**Comment by jamesmills** [comment]
It should be live 

https://packagist.org/packages/jamesmills/laravel-notification-rate-limit#1.1.0

**Pull request merged**
